### ISSUE TITLE
How to Fix it ?

### ISSUE THREAD

**Issue by KaiJia2017** [joshmoody24/sitcom-simulator#11]
Traceback (most recent call last):
  File "G:\Miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "G:\Miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\Miniconda3\Scripts\sitcom-simulator.exe\__main__.py", line 4, in <module>
  File "G:\Miniconda3\lib\site-packages\sitcom_simulator\__init__.py", line 4, in <module>
    from .script_generator import write_script, script_from_file
  File "G:\Miniconda3\lib\site-packages\sitcom_simulator\script_generator\__init__.py", line 1, in <module>
    from .script_generator import write_script, script_from_file
  File "G:\Miniconda3\lib\site-packages\sitcom_simulator\script_generator\script_generator.py", line 5, in <module>
    from ..user_input import select_characters as debug_select_characters
  File "G:\Miniconda3\lib\site-packages\sitcom_simulator\user_input.py", line 1, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

**Comment by joshmoody24** [comment]
What version of python are you running? [Sitcom Simulator requires >= 3.11](https://joshmoody24.github.io/sitcom-simulator/installation.html#dependencies)
`python --version`

If you have to use an older version, I can look into making it compatible with older versions. Let me know :)

**Comment by KaiJia2017** [comment]
![image](https://github.com/joshmoody24/sitcom-simulator/assets/32702706/e86aded4-839f-40c2-a098-77289e21cbca)
Yes，python version 3.11.5

**Comment by joshmoody24** [comment]
The reason you can't `pip install tomllib` is because it is a [built-in library in Python 3.11](https://docs.python.org/3.11/library/tomllib.html). It should automatically be available for use without having to install anything. I can't find any sources online where people have been unable to use it.

A few things to check:
- Do you have multiple versions installed? Maybe they're not playing nicely together.
- Are you using a virtual environment? If so, is it also using Python 3.11?

After that, my only other idea would be reinstalling python to see if that fixes it. Sorry it isn't working, I'll keep trying to help!

**Comment by KaiJia2017** [comment]
Thank you, I've fixed it

**Comment by joshmoody24** [comment]
Awesome! Glad you got it working!
